package nlquery

// NLQueryRequest is the incoming request for a natural language query.
type NLQueryRequest struct {
	Question       string `json:"question"`
	ConversationID string `json:"conversation_id,omitempty"`
}

// NLQueryResponse is the structured response returned for a natural language query.
type NLQueryResponse struct {
	Answer        string                   `json:"answer"`
	Data          []map[string]interface{} `json:"data,omitempty"`
	Visualization *VisualizationHint       `json:"visualization,omitempty"`
	Sources       []string                 `json:"sources"`
	QueryPlan     *QueryPlan               `json:"query_plan,omitempty"`
}

// QueryPlan represents the structured plan generated by the LLM to answer a question.
type QueryPlan struct {
	Steps        []QueryStep `json:"steps"`
	AnswerFormat string      `json:"answer_format"`
}

// QueryStep is a single step in the query execution plan.
// Type can be "graph_query", "api_call", or "aggregate".
type QueryStep struct {
	Type   string            `json:"type"`
	Params map[string]string `json:"params"`
}

// VisualizationHint suggests how the response data should be visualized.
type VisualizationHint struct {
	Type string `json:"type"` // "bar_chart", "table", "graph", "none"
	X    string `json:"x,omitempty"`
	Y    string `json:"y,omitempty"`
}

// StepResult holds the outcome of executing a single QueryStep.
type StepResult struct {
	Step    QueryStep
	Data    []map[string]interface{}
	Success bool
	Error   string
}
